### ISSUE TITLE
Prevent that trait covariances are grabbed by uni2mat

### ISSUE THREAD

**Issue by jkillisch** [susanne-frick/MFCblockInfo#2]
When the item.identifier of uni2mat matches the latent trait names _and_ the item names, uni2mat will create a diagonal matrix that includes the latent covariances and uniquenesses without a warning.

Example:
If pairs are labelled "I1I2", "I1I3", ... it seems intuitive to use the item.identifier "I". However, if traits are labelled "TRAIT1", "TRAIT2", ...,  their covariances will also be selected and included in the diagonal matrix of item uniquenesses without a warning.

Here is the head of mplus.pars[grepl(".WITH", mplus.pars$paramHeader) & grepl(item.identifier, mplus.pars$param), ] in that case:

![Bildschirmfoto 2024-10-01 um 23 57 44](https://github.com/user-attachments/assets/6936f47e-6d04-4f28-b52b-c67e0e548276)

I assume that the first 10 lines shouldn't be selected.

It would be great if the function automatically excluded the latent covariances. As a quick fix, the documentation could be extended to state that item.identifier must not match the latent trait names.

**Comment by susanne-frick** [comment]
Thank you for your hint. I have updated the documentation to emphasize that the regular expression should be used appropriately. Implementing a warning would not be in line with the idea of the function. For example, in you case item.identifier = "^I" would be a solution.
